[package]
name = "forward"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
aya = { version = "0.12" }
signal-hook = "0.3"